# Generated by Django 4.1.3 on 2023-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_district_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, default='null', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
