# Generated by Django 4.1.3 on 2023-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='district',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
