# Generated by Django 4.1.6 on 2023-02-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_district_customuser_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
