# Generated by Django 4.1.6 on 2023-02-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zone_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='district_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
