# Generated by Django 4.1.2 on 2022-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enconters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('total_encounters', models.CharField(max_length=100)),
                ('encounter_date', models.CharField(max_length=100)),
            ],
        ),
    ]
