# Generated by Django 4.1.2 on 2022-10-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_options_alter_facility_table'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enconters',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='enconters',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AlterModelTable(
            name='enconters',
            table='enconters',
        ),
    ]
