# Generated by Django 4.1.2 on 2022-10-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_alter_enconters_options_alter_enconters_facility_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enconters',
            table='encounters_enconters',
        ),
    ]
