# Generated by Django 4.1.2 on 2022-10-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_enconters_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enconters',
            old_name='facility_id',
            new_name='facility',
        ),
    ]
