# Generated by Django 4.1.2 on 2022-10-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_rename_facility_id_enconters_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enconters',
            old_name='facility',
            new_name='facility_id',
        ),
        migrations.AlterModelTable(
            name='enconters',
            table='encounters',
        ),
    ]
