# Generated by Django 4.1.2 on 2022-10-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0005_rename_facility_enconters_facility_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enconters',
            old_name='facility_id',
            new_name='facility',
        ),
    ]
