# Generated by Django 4.1.2 on 2022-10-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0008_alter_enconters_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enconters',
            old_name='facility',
            new_name='facility_id',
        ),
    ]
