# Generated by Django 4.1.3 on 2022-11-18 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0010_rename_facility_id_enconters_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='enconters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enconters',
            name='total_patients',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enconters',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
