# Generated by Django 4.1.3 on 2023-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0011_enconters_created_at_enconters_total_patients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enconters',
            name='district_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
