# Generated by Django 4.1.3 on 2023-01-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0012_enconters_district_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enconters',
            name='district_id',
        ),
    ]
