# Generated by Django 4.1.6 on 2023-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0013_remove_enconters_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enconters',
            name='total_encounters',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='enconters',
            name='total_patients',
            field=models.BigIntegerField(),
        ),
    ]
