# Generated by Django 4.1.6 on 2023-02-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_load', '0003_viralload_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viralload',
            name='acknowledgement_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
