# Generated by Django 3.2.18 on 2023-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_load', '0004_alter_viralload_acknowledgement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viralload',
            name='ordered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='viralload',
            name='released_date',
            field=models.DateTimeField(null=True),
        ),
    ]
