# Generated by Django 3.2.18 on 2023-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_load', '0005_auto_20230515_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralload',
            name='order_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='viralload',
            name='test_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
