# Generated by Django 4.1.2 on 2022-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
