# Generated by Django 4.1.2 on 2022-10-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_options_alter_facility_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='facilities_facility',
        ),
    ]
