# Generated by Django 4.1.2 on 2022-10-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='facilities',
        ),
    ]
