# Generated by Django 3.2.16 on 2022-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facility_created_at_facility_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='ip_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
