# Generated by Django 4.1.3 on 2023-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_facility_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='district_id',
            field=models.BigIntegerField(),
        ),
    ]
