# Generated by Django 4.1.6 on 2023-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_alter_facility_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
