# Generated by Django 3.2.18 on 2023-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_facility_viral_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='dde_enabled',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
