# Generated by Django 3.2.18 on 2023-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_facility_dde_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='close_monitoring_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='get_device_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
