# Generated by Django 3.2.18 on 2024-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_auto_20230630_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ip_address_iblis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='password_iblis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='user_name_iblis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
