# Generated by Django 4.1.2 on 2022-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(blank=True, max_length=100)),
                ('vpn_status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vpn',
                'managed': True,
            },
        ),
    ]
