# Generated by Django 4.1.2 on 2022-10-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_facility_table'),
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='facility_id',
        ),
        migrations.AddField(
            model_name='vpn',
            name='facility',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
            preserve_default=False,
        ),
    ]
