# Generated by Django 4.1.3 on 2023-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_remove_vpn_facility_id_vpn_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='vpn_sms_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
