# Generated by Django 4.1.3 on 2023-01-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_vpn_vpn_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='vpn_sms_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
