# Generated by Django 4.1.3 on 2023-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_alter_vpn_vpn_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
