# Generated by Django 4.1.6 on 2023-03-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_alter_vpn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='end_down_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vpn',
            name='start_down_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
