# Generated by Django 3.2.18 on 2023-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_vpn_down_time_vpn_response_time_vpn_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='response_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
