# Generated by Django 4.1.6 on 2023-03-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_vpn_down_time_vpn_response_time_vpn_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='down_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='response_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='up_time',
            field=models.BigIntegerField(),
        ),
    ]
