# Generated by Django 3.2.18 on 2023-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_vpn_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='received_bandwidth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vpn',
            name='transmitted_bandwidth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
