# Generated by Django 4.1.6 on 2023-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_alter_vpn_down_time_alter_vpn_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='down_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='response_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='up_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
