# Generated by Django 4.1.6 on 2023-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_alter_vpn_down_time_alter_vpn_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='response_time',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
