# Generated by Django 4.1.6 on 2023-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_alter_vpn_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='response_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
