# Generated by Django 4.1.6 on 2023-03-25 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_alter_vpn_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='down_time',
        ),
        migrations.RemoveField(
            model_name='vpn',
            name='up_time',
        ),
        migrations.AddField(
            model_name='vpn',
            name='end_down_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpn',
            name='start_down_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
