# Generated by Django 4.1.6 on 2023-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0012_remove_vpn_down_time_remove_vpn_up_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='end_down_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='start_down_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
