# Generated by Django 4.1.3 on 2023-01-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0007_alter_facility_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPN_TEMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'db_table': 'vpn_temp',
                'managed': True,
            },
        ),
    ]
