# Generated by Django 4.1.2 on 2022-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility_name', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('database_username', models.CharField(max_length=100)),
                ('server_ip_address', models.CharField(max_length=100)),
                ('database_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'databases',
                'managed': True,
            },
        ),
    ]
