# Generated by Django 4.1.2 on 2022-11-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databases',
            old_name='Facility_name',
            new_name='facility_name',
        ),
    ]
