# Generated by Django 4.1.3 on 2022-11-18 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_rename_facility_name_databases_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
