# Generated by Django 3.2.18 on 2023-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_databases_created_at_databases_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='databases',
            name='dump_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databases',
            name='progress',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databases',
            name='database_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='databases',
            name='database_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='databases',
            name='database_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='databases',
            name='server_ip_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
